/*
 * Tceon.com Inc.
 * Copyright (c) 2009 All Rights Reserved.
 */
package com.tccz.loan.common.dal.dataobject;

// auto generated imports
import java.util.Date;

/**
 * A data object class directly models database table <tt>loan</tt>.
 *
 * This file is generated by <tt>paygw-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/loan.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>paygw-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class LoanDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>loaner</tt>.
	 */
	private String loaner;

	/**
	 * This property corresponds to db column <tt>executor</tt>.
	 */
	private String executor;

	/**
	 * This property corresponds to db column <tt>amount</tt>.
	 */
	private long amount;

	/**
	 * This property corresponds to db column <tt>currency</tt>.
	 */
	private String currency;

	/**
	 * This property corresponds to db column <tt>term</tt>.
	 */
	private int term;

	/**
	 * This property corresponds to db column <tt>annual_rate</tt>.
	 */
	private String annualRate;

	/**
	 * This property corresponds to db column <tt>first_repayment_date</tt>.
	 */
	private Date firstRepaymentDate;

	/**
	 * This property corresponds to db column <tt>repayment_mode</tt>.
	 */
	private String repaymentMode;

	/**
	 * This property corresponds to db column <tt>repayment_config</tt>.
	 */
	private String repaymentConfig;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>loaner</tt>.
     *
     * @return property value of loaner
     */
	public String getLoaner() {
		return loaner;
	}
	
	/**
	 * Setter method for property <tt>loaner</tt>.
	 * 
	 * @param loaner value to be assigned to property loaner
     */
	public void setLoaner(String loaner) {
		this.loaner = loaner;
	}

    /**
     * Getter method for property <tt>executor</tt>.
     *
     * @return property value of executor
     */
	public String getExecutor() {
		return executor;
	}
	
	/**
	 * Setter method for property <tt>executor</tt>.
	 * 
	 * @param executor value to be assigned to property executor
     */
	public void setExecutor(String executor) {
		this.executor = executor;
	}

    /**
     * Getter method for property <tt>amount</tt>.
     *
     * @return property value of amount
     */
	public long getAmount() {
		return amount;
	}
	
	/**
	 * Setter method for property <tt>amount</tt>.
	 * 
	 * @param amount value to be assigned to property amount
     */
	public void setAmount(long amount) {
		this.amount = amount;
	}

    /**
     * Getter method for property <tt>currency</tt>.
     *
     * @return property value of currency
     */
	public String getCurrency() {
		return currency;
	}
	
	/**
	 * Setter method for property <tt>currency</tt>.
	 * 
	 * @param currency value to be assigned to property currency
     */
	public void setCurrency(String currency) {
		this.currency = currency;
	}

    /**
     * Getter method for property <tt>term</tt>.
     *
     * @return property value of term
     */
	public int getTerm() {
		return term;
	}
	
	/**
	 * Setter method for property <tt>term</tt>.
	 * 
	 * @param term value to be assigned to property term
     */
	public void setTerm(int term) {
		this.term = term;
	}

    /**
     * Getter method for property <tt>annualRate</tt>.
     *
     * @return property value of annualRate
     */
	public String getAnnualRate() {
		return annualRate;
	}
	
	/**
	 * Setter method for property <tt>annualRate</tt>.
	 * 
	 * @param annualRate value to be assigned to property annualRate
     */
	public void setAnnualRate(String annualRate) {
		this.annualRate = annualRate;
	}

    /**
     * Getter method for property <tt>firstRepaymentDate</tt>.
     *
     * @return property value of firstRepaymentDate
     */
	public Date getFirstRepaymentDate() {
		return firstRepaymentDate;
	}
	
	/**
	 * Setter method for property <tt>firstRepaymentDate</tt>.
	 * 
	 * @param firstRepaymentDate value to be assigned to property firstRepaymentDate
     */
	public void setFirstRepaymentDate(Date firstRepaymentDate) {
		this.firstRepaymentDate = firstRepaymentDate;
	}

    /**
     * Getter method for property <tt>repaymentMode</tt>.
     *
     * @return property value of repaymentMode
     */
	public String getRepaymentMode() {
		return repaymentMode;
	}
	
	/**
	 * Setter method for property <tt>repaymentMode</tt>.
	 * 
	 * @param repaymentMode value to be assigned to property repaymentMode
     */
	public void setRepaymentMode(String repaymentMode) {
		this.repaymentMode = repaymentMode;
	}

    /**
     * Getter method for property <tt>repaymentConfig</tt>.
     *
     * @return property value of repaymentConfig
     */
	public String getRepaymentConfig() {
		return repaymentConfig;
	}
	
	/**
	 * Setter method for property <tt>repaymentConfig</tt>.
	 * 
	 * @param repaymentConfig value to be assigned to property repaymentConfig
     */
	public void setRepaymentConfig(String repaymentConfig) {
		this.repaymentConfig = repaymentConfig;
	}
}
