/*
 * Tceon.com Inc.
 * Copyright (c) 2009 All Rights Reserved.
 */
package com.tccz.loan.common.dal.daointerface;

// auto generated imports
import org.springframework.dao.DataAccessException;

import com.tccz.loan.common.dal.dataobject.LoanDO;
import com.tccz.loan.dal.util.PageList;

/**
 * A dao interface provides methods to access database table <tt>loan</tt>.
 *
 * This file is generated by <tt>paygw-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/loan.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>paygw-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public interface LoanDAO {
	/**
	 *  Query DB table <tt>loan</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from loan where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return LoanDO
	 *	@throws DataAccessException
	 */	 
    public LoanDO getById(int id) throws DataAccessException;

	/**
	 *  Insert one <tt>LoanDO</tt> object to DB table <tt>loan</tt>, return primary key
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into loan(loaner,executor,amount,currency,term,annual_rate,first_repayment_date,repayment_mode,repayment_config,create_time,release_date) values (?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, ?)</tt>
	 *
	 *	@param loan
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int insert(LoanDO loan) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>loan</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from loan where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int delete(int id) throws DataAccessException;

	/**
	 *  Query DB table <tt>loan</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from loan</tt>
	 *
	 *	@param loaner
	 *	@param pageSize
	 *	@param pageNum
	 *	@return PageList
	 *	@throws DataAccessException
	 */	 
    public PageList getByCondition(String loaner, int pageSize, int pageNum) throws DataAccessException;

}